name: firebase_padc
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-9.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  firebase_core: ^1.8.0
  firebase_database: ^8.0.1
  cloud_firestore: ^2.5.4
  firebase_storage: ^10.1.0
  firebase_auth: ^3.2.0
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.4
  firebase_analytics: ^8.3.4
  firebase_crashlytics: ^2.3.0
  firebase_performance: ^0.7.1+4
  firebase_remote_config: ^1.0.3
  firebase_in_app_messaging: ^0.6.0+5
  firebase_installations: ^16.3.6
  google_ml_kit: ^0.7.1
  image_picker: ^0.8.4+4
  loading_indicator: ^3.0.2
  cupertino_icons: ^1.0.2
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.4

flutter:
  uses-material-design: true
